CREATE TABLE files (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  data LONGBLOB NOT NULL,
  mime_type VARCHAR(255) NOT NULL);

ALTER TABLE `demo`.`files` 
ADD COLUMN `path` VARCHAR(45) NULL DEFAULT NULL AFTER `mime_type`,
CHANGE COLUMN `data` `data` LONGBLOB NULL DEFAULT NULL ;